// src/components-vue/adaptive/ModeSwitcher.vue
<template>
  <div class="flex items-center gap-3">
    <Label for="mode">Mode</Label>
    <Select v-model="selectedMode" placeholder="Select mode">
      <SelectItem value="Novice">Novice</SelectItem>
      <SelectItem value="Expert">Expert</SelectItem>
      <SelectItem value="Accessibility">Accessibility-First</SelectItem>
    </Select>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Select from '@/components-vue/ui/Select.vue';
import SelectItem from '@/components-vue/ui/SelectItem.vue';
import Label from '@/components-vue/ui/Label.vue';

export type Mode = 'Novice' | 'Expert' | 'Accessibility';

interface Props {
  mode: Mode;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  change: [mode: Mode];
}>();

const selectedMode = computed({
  get: () => props.mode,
  set: (value) => emit('change', value as Mode),
});
</script>

// src/components/adaptive/ModeSwitcher.tsx
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";

export type Mode = "Novice" | "Expert" | "Accessibility";

interface ModeSwitcherProps {
  mode: Mode;
  onChange: (mode: Mode) => void;
}

const ModeSwitcher = ({ mode, onChange }: ModeSwitcherProps) => {
  return (
    <div className="flex items-center gap-3">
      <Label htmlFor="mode">Mode</Label>
      <Select value={mode} onValueChange={(v) => onChange(v as Mode)}>
        <SelectTrigger id="mode" className="w-40">
          <SelectValue placeholder="Select mode" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="Novice">Novice</SelectItem>
          <SelectItem value="Expert">Expert</SelectItem>
          <SelectItem value="Accessibility">Accessibility-First</SelectItem>
        </SelectContent>
      </Select>
    </div>
  );
};

export default ModeSwitcher;
