// src/components/chat/MessageBubble.tsx
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Lightbulb } from "lucide-react";
import { ReactNode } from "react";

export type ChatMessage = {
  id: string;
  role: "user" | "ai";
  content: ReactNode;
  explainable?: boolean;
};

interface MessageBubbleProps {
  message: ChatMessage;
  onExplain?: (id: string) => void;
}

const MessageBubble = ({ message, onExplain }: MessageBubbleProps) => {
  const isUser = message.role === "user";
  return (
    <div className={cn("flex w-full", isUser ? "justify-end" : "justify-start")}> 
      <Card
        className={cn(
          "max-w-[85%] md:max-w-[70%] px-4 py-3 border transition-shadow",
          isUser
            ? "bg-primary text-primary-foreground shadow-sm"
            : "bg-muted text-foreground"
        )}
      >
        <div className="text-sm leading-relaxed">{message.content}</div>
        {message.explainable && !isUser && (
          <div className="mt-2 flex justify-end">
            <Button size="sm" variant="glow" onClick={() => onExplain?.(message.id)}>
              <Lightbulb className="mr-2" /> Explain
            </Button>
          </div>
        )}
      </Card>
    </div>
  );
};

export default MessageBubble;

// src/components/chat/MessageBubble.vue
<template>
  <div
    class="p-4 rounded-lg"
    :class="message.role === 'user' ? 'bg-primary text-primary-foreground ml-8' : 'bg-muted mr-8'"
  >
    <div class="flex justify-between items-start gap-2">
      <p class="text-sm">{{ message.content }}</p>
      <button
        v-if="message.explainable"
        @click="$emit('explain', message.id)"
        class="text-xs px-2 py-1 rounded bg-background/10 hover:bg-background/20 transition-colors whitespace-nowrap"
      >
        Explain
      </button>
    </div>
    <div v-if="message.timestamp" class="text-xs opacity-70 mt-2">
      {{ formatTime(message.timestamp) }}
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ChatMessage } from '../../stores/chat'

defineProps<{
  message: ChatMessage
}>()

defineEmits<{
  explain: [id: string]
}>()

function formatTime(date: Date) {
  return new Date(date).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })
}
</script>
