// src/components-vue/shared/TransparencyIndicator.vue
<template>
  <div class="inline-flex items-center gap-2 rounded-md border border-border bg-card px-2 py-1 text-xs text-muted-foreground">
    <ShieldCheck class="h-4 w-4 text-accent" />
    Transparent AI
  </div>
</template>

<script setup lang="ts">
import { ShieldCheck } from 'lucide-vue-next';
</script>

// src/components/shared/TransparencyIndicator.tsx
import { ShieldCheck } from "lucide-react";

const TransparencyIndicator = () => {
  return (
    <div className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-2 py-1 text-xs text-muted-foreground">
      <ShieldCheck className="h-4 w-4 text-accent" />
      Transparent AI
    </div>
  );
};

export default TransparencyIndicator;
